#!/usr/bin/env python3
"""Batch 2 of UPSC topic explainers — economic terms, schemes, bodies,
organisations, indices, acts. Original factual content. Reuses _gen_topics TMPL.
Run from repo root: python3 _gen_topics2.py
"""
import os, importlib.util
spec = importlib.util.spec_from_file_location("gt", os.path.join(os.path.dirname(os.path.abspath(__file__)), "_gen_topics.py"))
gt = importlib.util.module_from_spec(spec); spec.loader.exec_module(gt)
TMPL, esc, BASE, TODAY, ROOT = gt.TMPL, gt.esc, gt.BASE, gt.TODAY, gt.ROOT

def P(slug, tag, title, kw, desc, intro, sec, why, faq, cta="/pyq/economy/", read="5 min read"):
    return {"slug":slug,"tag":tag,"title":title,"kw":kw,"desc":desc,"intro":intro,"sec":sec,"why":why,"faq":faq,"cta":cta,"read":read}

T = [
 P("current-account-deficit-cad","Economy","Current Account Deficit (CAD) Explained",
   "current account deficit UPSC, CAD, balance of payments, trade deficit, forex",
   "Current Account Deficit explained for UPSC — what the current account records, when a CAD arises, and why it matters for the rupee and forex reserves.",
   "The Current Account Deficit (CAD) occurs when the value of a country's imports of goods, services and transfers exceeds the value of its exports — meaning it is a net borrower from the rest of the world.",
   [("What the current account records","The current account records trade in goods (merchandise), services (like software and tourism), and net income and transfers (such as remittances). A deficit means outflows exceed inflows on these items."),
    ("Why it matters","A high CAD can pressure the rupee and draw down foreign-exchange reserves, so it is watched closely. It is often financed by capital inflows like FDI and FPI.")],
   "The current account, CAD and its financing via the capital account are core Economy topics that recur in Prelims statement-based questions.",
   [("What is a Current Account Deficit?","It arises when a country's imports of goods, services and transfers exceed its exports — a net outflow on the current account."),
    ("How is a CAD financed?","Usually through capital-account inflows such as foreign direct investment (FDI) and foreign portfolio investment (FPI).")]),

 P("balance-of-payments-bop","Economy","Balance of Payments (BoP) Explained",
   "balance of payments UPSC, BoP, current account capital account, forex reserves",
   "Balance of Payments explained for UPSC — the record of all economic transactions between a country and the rest of the world, split into current and capital accounts.",
   "The Balance of Payments (BoP) is a systematic record of all economic transactions between residents of a country and the rest of the world over a period.",
   [("Two main accounts","The BoP has two main accounts: the current account (trade in goods and services, income and transfers) and the capital (and financial) account (investments, loans and reserves)."),
    ("Balancing item","In principle the BoP always balances; changes in foreign-exchange reserves absorb any gap. A surplus builds reserves, while a deficit draws them down.")],
   "The structure of the BoP — current vs capital account and the role of reserves — is a reliably tested Economy concept.",
   [("What are the two main accounts of the BoP?","The current account and the capital (and financial) account."),
    ("What absorbs a gap in the Balance of Payments?","Changes in foreign-exchange reserves.")]),

 P("foreign-direct-investment-fdi","Economy","Foreign Direct Investment (FDI) Explained",
   "FDI UPSC, foreign direct investment, automatic route government route, FPI vs FDI",
   "FDI explained for UPSC — investment that gives lasting control in an enterprise, the automatic and government routes, and how it differs from FPI.",
   "Foreign Direct Investment (FDI) is investment made by a foreign entity to acquire a lasting interest and management influence in a business in another country.",
   [("Routes of entry","In India, FDI comes in through two routes: the automatic route (no prior government approval needed, within sectoral caps) and the government route (prior approval required for sensitive sectors)."),
    ("FDI vs FPI","Unlike Foreign Portfolio Investment (FPI), which is passive investment in financial assets, FDI involves control and is considered more stable ('patient capital').")],
   "The FDI routes and the FDI–FPI distinction are frequently tested Economy facts.",
   [("What are the two routes for FDI in India?","The automatic route and the government (approval) route."),
    ("How does FDI differ from FPI?","FDI involves lasting control and management interest, while FPI is passive portfolio investment in financial assets.")]),

 P("non-performing-assets-npa","Economy","Non-Performing Assets (NPA) Explained",
   "NPA UPSC, non-performing assets, bad loans, gross net NPA, banking stress",
   "NPAs explained for UPSC — when a loan becomes non-performing, the categories of stressed assets, and why NPAs strain banks.",
   "A Non-Performing Asset (NPA) is a loan or advance for which the principal or interest payment remains overdue for a specified period — generally 90 days.",
   [("Classification","Stressed assets are classified as sub-standard, doubtful or loss assets depending on how long they remain non-performing. Gross NPA is the total, and net NPA is gross NPA minus provisions."),
    ("Why they matter","High NPAs reduce banks' profitability and lending capacity, which is why mechanisms like the Insolvency and Bankruptcy Code help resolve bad loans.")],
   "NPA definitions (the 90-day rule, gross vs net) and resolution mechanisms are commonly tested banking topics.",
   [("When does a loan become an NPA?","Generally when principal or interest is overdue for 90 days or more."),
    ("What is the difference between gross and net NPA?","Gross NPA is the total non-performing assets, while net NPA is gross NPA minus provisions made against them.")]),

 P("frbm-act","Economy","FRBM Act Explained: Fiscal Responsibility",
   "FRBM Act UPSC, Fiscal Responsibility Budget Management, fiscal deficit target, fiscal discipline",
   "The FRBM Act explained for UPSC — the law that institutionalises fiscal discipline by setting targets for deficits and public debt.",
   "The Fiscal Responsibility and Budget Management (FRBM) Act, 2003, is a law aimed at ensuring fiscal discipline by setting targets for the government's deficits and debt.",
   [("Objectives","The Act seeks to reduce the fiscal deficit, improve macroeconomic management and ensure inter-generational equity by limiting how much the government borrows."),
    ("Escape clause","The Act includes an 'escape clause' allowing deviation from targets in specified exceptional circumstances, such as national security or severe economic distress.")],
   "The FRBM Act's purpose and its escape clause are commonly tested in the context of fiscal policy.",
   [("What does the FRBM Act aim to do?","Institutionalise fiscal discipline by setting targets for the government's deficits and debt."),
    ("What is the FRBM escape clause?","A provision allowing the government to deviate from fiscal targets in specified exceptional situations.")]),

 P("gdp-vs-gnp","Economy","GDP vs GNP: Key Differences Explained",
   "GDP GNP UPSC, gross domestic product, gross national product, national income, NNP",
   "GDP vs GNP explained for UPSC — how the two measures of national income differ, and where net factor income from abroad fits in.",
   "Gross Domestic Product (GDP) and Gross National Product (GNP) are two key measures of a nation's economic output that differ in what they include.",
   [("The core difference","GDP measures the value of all goods and services produced within a country's borders. GNP adds net factor income from abroad — income earned by residents overseas minus income earned by foreigners domestically."),
    ("Related measures","Subtracting depreciation gives Net Domestic Product (NDP) or Net National Product (NNP). National income is usually measured as NNP at factor cost.")],
   "The GDP–GNP distinction and the role of net factor income from abroad are classic Economy Prelims topics.",
   [("What is the difference between GDP and GNP?","GDP measures output within a country's borders; GNP adds net factor income earned by residents from abroad."),
    ("What is Net National Product?","GNP minus depreciation (consumption of fixed capital).")]),

 P("direct-and-indirect-taxes","Economy","Direct and Indirect Taxes Explained",
   "direct indirect taxes UPSC, income tax GST, progressive regressive tax, taxation India",
   "Direct and indirect taxes explained for UPSC — how they differ in incidence, examples of each, and their progressive or regressive nature.",
   "Taxes in India are broadly classified as direct taxes and indirect taxes, based on who bears the burden.",
   [("Direct taxes","Direct taxes are levied directly on income or wealth and cannot be shifted to another person — for example, income tax and corporation tax. They are generally progressive."),
    ("Indirect taxes","Indirect taxes are levied on goods and services and can be passed on to the consumer — for example, GST and customs duty. They tend to be regressive as they fall equally on all consumers.")],
   "The direct/indirect classification and progressive vs regressive nature are standard Economy Prelims facts.",
   [("What is a direct tax?","A tax levied directly on income or wealth whose burden cannot be shifted, such as income tax."),
    ("Are indirect taxes progressive or regressive?","They tend to be regressive, as they apply equally to all consumers regardless of income.")]),

 P("purchasing-power-parity-ppp","Economy","Purchasing Power Parity (PPP) Explained",
   "PPP UPSC, purchasing power parity, exchange rate, GDP PPP, cost of living",
   "PPP explained for UPSC — how purchasing power parity compares economies by adjusting for price differences across countries.",
   "Purchasing Power Parity (PPP) is a method of comparing economies and currencies by accounting for differences in the cost of goods and services between countries.",
   [("The idea","PPP suggests that in the long run, exchange rates should adjust so that an identical basket of goods costs the same across countries. GDP measured at PPP reflects real purchasing power."),
    ("Why it matters","When measured at PPP, developing economies like India appear larger relative to their market-exchange-rate GDP, because prices there are generally lower.")],
   "GDP at PPP versus market exchange rates is a commonly tested Economy concept.",
   [("What does Purchasing Power Parity measure?","It compares economies by adjusting for differences in the cost of goods and services across countries."),
    ("Why is India's GDP larger at PPP?","Because prices for many goods and services are lower in India, so a given income buys more.")]),

 P("gini-coefficient-explained","Economy","Gini Coefficient and Lorenz Curve Explained",
   "Gini coefficient UPSC, Lorenz curve, income inequality, distribution measure",
   "The Gini coefficient explained for UPSC — how it measures income or wealth inequality using the Lorenz curve.",
   "The Gini coefficient is a widely used measure of income or wealth inequality within a population, derived from the Lorenz curve.",
   [("How it works","The Gini coefficient ranges from 0 to 1: a value of 0 means perfect equality (everyone has the same income) and 1 means perfect inequality (one person has all the income)."),
    ("The Lorenz curve","The Lorenz curve plots the cumulative share of income against the cumulative share of the population; the further it bows away from the line of equality, the greater the inequality.")],
   "The Gini coefficient's 0–1 scale and its link to the Lorenz curve are commonly tested inequality concepts.",
   [("What does a Gini coefficient of 0 mean?","Perfect equality — everyone has the same income."),
    ("What is the Lorenz curve?","A graph showing the cumulative share of income against the cumulative share of population, used to derive the Gini coefficient.")]),

 P("money-supply-m0-m3","Economy","Money Supply (M0 to M3) Explained",
   "money supply UPSC, M0 M1 M2 M3, reserve money, broad money, monetary aggregates",
   "Money supply explained for UPSC — the monetary aggregates M0 to M3, from reserve money to broad money.",
   "Money supply refers to the total stock of money in circulation in an economy, measured through monetary aggregates M0 to M3.",
   [("The aggregates","M0 is reserve money (currency in circulation plus bankers' deposits with the RBI). M1 (narrow money) is currency with the public plus demand deposits. M3 (broad money) adds time deposits and is the most commonly used measure."),
    ("Why it matters","Controlling money supply is central to monetary policy, as excess money growth can fuel inflation.")],
   "The definitions of M0, M1 and M3 (narrow vs broad money) are frequently tested Economy facts.",
   [("What is M3?","Broad money — narrow money (M1) plus time deposits with banks; the most commonly used measure of money supply."),
    ("What is M0?","Reserve money — currency in circulation plus bankers' deposits with the RBI.")]),

 P("crr-and-slr","Economy","CRR and SLR Explained",
   "CRR SLR UPSC, cash reserve ratio, statutory liquidity ratio, RBI tools, liquidity",
   "CRR and SLR explained for UPSC — the two reserve requirements the RBI uses to control liquidity in the banking system.",
   "The Cash Reserve Ratio (CRR) and Statutory Liquidity Ratio (SLR) are reserve requirements that banks must maintain, used by the RBI to manage liquidity.",
   [("Cash Reserve Ratio","CRR is the portion of a bank's deposits that must be kept as cash reserves with the RBI. Banks earn no interest on it, and raising CRR reduces the funds available for lending."),
    ("Statutory Liquidity Ratio","SLR is the portion of deposits banks must hold in safe, liquid assets like cash, gold or approved government securities, before lending.")],
   "The distinction between CRR and SLR — cash with the RBI vs liquid assets held by the bank — is a classic Economy Prelims topic.",
   [("What is the CRR?","The share of a bank's deposits that must be kept as cash reserves with the RBI."),
    ("How does SLR differ from CRR?","SLR is held by the bank itself in liquid assets like gold and government securities, whereas CRR is cash kept with the RBI.")]),

 P("insolvency-and-bankruptcy-code","Economy","Insolvency and Bankruptcy Code (IBC) Explained",
   "IBC UPSC, Insolvency Bankruptcy Code 2016, NCLT, resolution process, bad loans",
   "The IBC explained for UPSC — the time-bound framework for resolving insolvency of companies and individuals, and the role of the NCLT.",
   "The Insolvency and Bankruptcy Code (IBC), 2016, is a consolidated law that provides a time-bound process for resolving insolvency of companies, partnerships and individuals.",
   [("The process","When a company defaults, a corporate insolvency resolution process can be initiated before the National Company Law Tribunal (NCLT). A resolution professional manages the firm while creditors decide on a revival plan or liquidation."),
    ("Significance","The IBC shifted control from debtors to creditors and set strict timelines, helping address the problem of bad loans and improving the ease of doing business.")],
   "The IBC's time-bound resolution, the NCLT and its role in tackling NPAs are commonly tested economic-governance facts.",
   [("When was the Insolvency and Bankruptcy Code enacted?","In 2016."),
    ("Which tribunal handles corporate insolvency under the IBC?","The National Company Law Tribunal (NCLT).")]),

 P("disinvestment-explained","Economy","Disinvestment in India Explained",
   "disinvestment UPSC, PSU disinvestment, strategic sale, minority stake, privatisation",
   "Disinvestment explained for UPSC — the sale of government stakes in public-sector enterprises, its types and objectives.",
   "Disinvestment is the process by which the government sells or dilutes its stake in public-sector enterprises (PSUs).",
   [("Types","Minority disinvestment sells a small stake while the government retains control; strategic disinvestment (privatisation) sells a controlling stake and hands over management to a private buyer."),
    ("Objectives","Disinvestment aims to raise revenue, improve efficiency, reduce fiscal burden and broaden ownership. A dedicated department (DIPAM) manages the process.")],
   "The types of disinvestment (minority vs strategic) and its objectives are commonly tested Economy topics.",
   [("What is strategic disinvestment?","Selling a controlling stake in a PSU along with management control to a private entity."),
    ("Which department manages disinvestment in India?","The Department of Investment and Public Asset Management (DIPAM).")]),

 P("priority-sector-lending","Economy","Priority Sector Lending (PSL) Explained",
   "priority sector lending UPSC, PSL, RBI, agriculture MSME, financial inclusion",
   "Priority Sector Lending explained for UPSC — the RBI mandate requiring banks to lend a share of credit to priority sectors like agriculture and MSMEs.",
   "Priority Sector Lending (PSL) is an RBI requirement that banks direct a specified share of their lending to sectors considered important for inclusive growth.",
   [("Covered sectors","Priority sectors include agriculture, micro, small and medium enterprises (MSMEs), education, housing, renewable energy and weaker sections of society."),
    ("Purpose","PSL ensures that credit reaches sectors and groups that might otherwise be underserved, supporting financial inclusion and balanced development.")],
   "The PSL concept and its covered sectors are commonly tested banking and financial-inclusion facts.",
   [("What is Priority Sector Lending?","An RBI requirement that banks lend a specified share of credit to priority sectors like agriculture and MSMEs."),
    ("Why is PSL important?","It ensures credit reaches underserved but economically important sectors and groups, supporting financial inclusion.")]),

 P("depreciation-vs-devaluation","Economy","Depreciation vs Devaluation of Currency",
   "depreciation devaluation UPSC, rupee value, exchange rate regime, currency fall",
   "Depreciation vs devaluation explained for UPSC — how a currency's fall under a floating regime differs from a deliberate government cut under a fixed regime.",
   "Depreciation and devaluation both describe a fall in a currency's value, but they occur under different exchange-rate regimes.",
   [("Depreciation","Depreciation is a decline in a currency's value driven by market forces under a floating exchange-rate system — for example, when the rupee weakens against the dollar due to demand and supply."),
    ("Devaluation","Devaluation is a deliberate reduction of a currency's official value by the government or central bank under a fixed exchange-rate system.")],
   "The depreciation vs devaluation distinction (market-driven vs deliberate) is a commonly tested Economy concept.",
   [("What is currency depreciation?","A market-driven fall in a currency's value under a floating exchange-rate system."),
    ("How does devaluation differ from depreciation?","Devaluation is a deliberate official reduction of a currency's value under a fixed exchange-rate system, not a market outcome.")]),

 P("jal-jeevan-mission","Scheme","Jal Jeevan Mission Explained",
   "Jal Jeevan Mission UPSC, tap water connection, Har Ghar Jal, rural drinking water",
   "Jal Jeevan Mission explained for UPSC — the flagship scheme to provide functional household tap water connections to every rural home.",
   "The Jal Jeevan Mission aims to provide a functional household tap water connection to every rural household — the vision of 'Har Ghar Jal'.",
   [("Objective","The mission focuses on providing safe and adequate drinking water through individual tap connections to rural households, reducing the burden of fetching water, especially on women."),
    ("Approach","It emphasises community participation, source sustainability and local water management, and is implemented in partnership with states.")],
   "The Jal Jeevan Mission's 'Har Ghar Jal' goal and rural focus are commonly tested scheme facts.",
   [("What is the goal of the Jal Jeevan Mission?","To provide a functional household tap water connection to every rural home ('Har Ghar Jal')."),
    ("Who implements the Jal Jeevan Mission?","It is implemented by states in partnership with the central government.")]),

 P("pm-awas-yojana","Scheme","Pradhan Mantri Awas Yojana (PMAY) Explained",
   "PMAY UPSC, Pradhan Mantri Awas Yojana, housing for all, rural urban housing",
   "PMAY explained for UPSC — the flagship housing scheme aiming to provide affordable 'housing for all', with rural and urban components.",
   "The Pradhan Mantri Awas Yojana (PMAY) is the government's flagship housing scheme, aiming to provide affordable housing to eligible families.",
   [("Two components","PMAY has two arms: PMAY-Gramin (rural) for building pucca houses in villages, and PMAY-Urban for urban housing, including credit-linked subsidies and affordable housing in partnership."),
    ("Objective","The scheme targets 'housing for all', focusing on the poor and economically weaker sections, with features like basic amenities and beneficiary-led construction.")],
   "PMAY's two components (Gramin and Urban) and the 'housing for all' goal are commonly tested scheme facts.",
   [("What are the two components of PMAY?","PMAY-Gramin (rural) and PMAY-Urban."),
    ("What is the objective of PMAY?","To provide affordable 'housing for all', especially to the poor and weaker sections.")]),

 P("pm-gati-shakti","Scheme","PM Gati Shakti Explained: Infrastructure Master Plan",
   "PM Gati Shakti UPSC, national master plan, multimodal connectivity, logistics infrastructure",
   "PM Gati Shakti explained for UPSC — the national master plan for multimodal connectivity that integrates infrastructure planning across ministries.",
   "PM Gati Shakti is a national master plan for multimodal connectivity that aims to integrate the infrastructure planning of various ministries and departments on a single digital platform.",
   [("Integrated planning","It brings together railways, roads, ports, airports and other infrastructure on a common GIS-based platform, so projects are planned and executed in a coordinated, holistic manner."),
    ("Goal","The plan seeks to reduce logistics costs, remove bottlenecks and improve the efficiency of moving goods and people, supporting the National Logistics Policy.")],
   "PM Gati Shakti's multimodal, integrated-planning approach is a commonly tested infrastructure scheme.",
   [("What is PM Gati Shakti?","A national master plan for integrated, multimodal infrastructure planning across ministries on a single digital platform."),
    ("What is a key goal of PM Gati Shakti?","To reduce logistics costs and improve connectivity by coordinating infrastructure planning.")]),

 P("production-linked-incentive-pli","Scheme","Production Linked Incentive (PLI) Scheme Explained",
   "PLI scheme UPSC, production linked incentive, manufacturing, Atmanirbhar Bharat, incentives",
   "The PLI scheme explained for UPSC — how it offers incentives on incremental production to boost domestic manufacturing across key sectors.",
   "The Production Linked Incentive (PLI) scheme provides financial incentives to companies based on incremental sales of goods manufactured in India, to boost domestic manufacturing.",
   [("How it works","Under PLI, eligible companies receive incentives linked to their increase in production or sales over a base year, encouraging investment and scale in targeted sectors."),
    ("Sectors","PLI schemes cover sectors such as electronics, pharmaceuticals, automobiles, telecom and solar modules, aligning with the Atmanirbhar Bharat vision of self-reliance.")],
   "The PLI scheme's design (incentives on incremental production) and its link to manufacturing self-reliance are commonly tested Economy topics.",
   [("What does the PLI scheme incentivise?","Incremental production or sales of goods manufactured in India."),
    ("What is the aim of the PLI scheme?","To boost domestic manufacturing and self-reliance across key sectors.")]),

 P("startup-india-explained","Scheme","Startup India Initiative Explained",
   "Startup India UPSC, startup ecosystem, DPIIT recognition, tax benefits, innovation",
   "Startup India explained for UPSC — the flagship initiative to nurture innovation and startups through simpler rules, funding support and tax benefits.",
   "Startup India is a flagship initiative to build a strong ecosystem for nurturing innovation and startups in the country.",
   [("Support offered","It offers benefits such as self-certification, tax exemptions for eligible startups, easier compliance, and access to funding through a Fund of Funds for Startups."),
    ("Recognition","Startups recognised by the Department for Promotion of Industry and Internal Trade (DPIIT) can avail these benefits, helping India become one of the world's largest startup ecosystems.")],
   "Startup India's benefits and DPIIT recognition are commonly tested economy and governance facts.",
   [("What does Startup India offer?","Simpler compliance, tax benefits, and funding support to build a strong startup ecosystem."),
    ("Which body recognises startups for benefits?","The Department for Promotion of Industry and Internal Trade (DPIIT).")]),

 P("make-in-india","Scheme","Make in India Initiative Explained",
   "Make in India UPSC, manufacturing, ease of doing business, FDI, self-reliance",
   "Make in India explained for UPSC — the initiative to boost domestic manufacturing, attract investment and make India a global manufacturing hub.",
   "Make in India is an initiative launched to encourage companies to manufacture in India and to make the country a global manufacturing and investment hub.",
   [("Objectives","It aims to boost manufacturing's share in the economy, create jobs, attract foreign investment and improve the ease of doing business across key sectors."),
    ("Approach","The initiative focuses on facilitation, infrastructure and reforms, and complements later programmes like PLI and Atmanirbhar Bharat.")],
   "Make in India's manufacturing and investment goals are commonly tested economy topics.",
   [("What is the aim of Make in India?","To boost domestic manufacturing, attract investment and make India a global manufacturing hub."),
    ("How does Make in India relate to Atmanirbhar Bharat?","Both aim to strengthen domestic manufacturing and self-reliance, with PLI schemes supporting these goals.")]),

 P("pm-mudra-yojana","Scheme","Pradhan Mantri Mudra Yojana (PMMY) Explained",
   "Mudra Yojana UPSC, PMMY, micro units, Shishu Kishor Tarun, collateral free loan",
   "PM Mudra Yojana explained for UPSC — the scheme providing collateral-free loans to micro and small non-corporate enterprises.",
   "The Pradhan Mantri Mudra Yojana (PMMY) provides collateral-free institutional credit to micro and small non-corporate, non-farm enterprises.",
   [("Loan categories","Loans are given in three categories based on the stage of the business: Shishu (smallest loans), Kishor (mid-range) and Tarun (largest). They are routed through banks and financial institutions."),
    ("Purpose","The scheme supports small entrepreneurs, income-generating activities and self-employment, promoting financial inclusion.")],
   "The Mudra loan categories (Shishu, Kishor, Tarun) and the collateral-free feature are commonly tested scheme facts.",
   [("What are the three categories of Mudra loans?","Shishu, Kishor and Tarun, based on loan size and business stage."),
    ("Are Mudra loans collateral-free?","Yes. PMMY provides collateral-free credit to eligible micro and small enterprises.")]),

 P("swachh-bharat-mission","Scheme","Swachh Bharat Mission Explained",
   "Swachh Bharat Mission UPSC, sanitation, open defecation free, toilets, waste management",
   "Swachh Bharat Mission explained for UPSC — the nationwide cleanliness and sanitation campaign, its rural and urban arms, and the ODF goal.",
   "The Swachh Bharat Mission is a nationwide campaign to improve sanitation and cleanliness, with rural and urban components.",
   [("Goals","Its first phase focused on eliminating open defecation by building toilets and changing behaviour, leading to many areas being declared Open Defecation Free (ODF). Later phases focus on solid and liquid waste management and sustaining ODF status."),
    ("Significance","The mission links sanitation to health, dignity and environmental outcomes, and is one of the largest such campaigns globally.")],
   "The Swachh Bharat Mission's ODF goal and its focus on waste management in later phases are commonly tested topics.",
   [("What does ODF stand for in the Swachh Bharat Mission?","Open Defecation Free."),
    ("What do the later phases of Swachh Bharat focus on?","Solid and liquid waste management and sustaining ODF status.")]),

 P("pm-fasal-bima-yojana","Scheme","PM Fasal Bima Yojana (Crop Insurance) Explained",
   "PM Fasal Bima Yojana UPSC, crop insurance, PMFBY, farmers, premium subsidy",
   "PMFBY explained for UPSC — the crop insurance scheme that protects farmers against crop loss from natural calamities, pests and diseases.",
   "The Pradhan Mantri Fasal Bima Yojana (PMFBY) is a crop insurance scheme that provides financial support to farmers suffering crop loss or damage.",
   [("Coverage","It covers losses from non-preventable natural risks such as drought, flood, pests and diseases, from pre-sowing to post-harvest for notified crops."),
    ("Premium","Farmers pay a low, fixed share of the premium (with different caps for kharif, rabi and commercial or horticultural crops), while the government subsidises the rest.")],
   "PMFBY's coverage and low farmer-premium design are commonly tested agriculture-scheme facts.",
   [("What does PMFBY insure against?","Crop loss or damage from non-preventable natural risks like drought, flood, pests and diseases."),
    ("Who pays most of the premium under PMFBY?","The government subsidises most of the premium; farmers pay a low fixed share.")]),

 P("skill-india-mission","Scheme","Skill India Mission Explained",
   "Skill India UPSC, skill development, PMKVY, vocational training, employability",
   "Skill India explained for UPSC — the mission to train people in employable skills, including the PMKVY flagship scheme.",
   "The Skill India Mission is a national effort to train a large number of people in industry-relevant skills to improve employability and productivity.",
   [("Key scheme","A flagship component is the Pradhan Mantri Kaushal Vikas Yojana (PMKVY), which provides short-term skill training and certification, including recognition of prior learning."),
    ("Ecosystem","The mission works through the National Skill Development Corporation, sector skill councils and training institutes to align skilling with industry needs.")],
   "Skill India and PMKVY are commonly tested in the context of human capital and employment.",
   [("What is the flagship scheme under Skill India?","The Pradhan Mantri Kaushal Vikas Yojana (PMKVY)."),
    ("What is the aim of the Skill India Mission?","To train people in employable, industry-relevant skills to boost employability.")]),

 P("poshan-abhiyaan","Scheme","POSHAN Abhiyaan Explained",
   "POSHAN Abhiyaan UPSC, nutrition mission, stunting, malnutrition, ICDS",
   "POSHAN Abhiyaan explained for UPSC — the national nutrition mission to reduce malnutrition, stunting and anaemia through a convergent approach.",
   "POSHAN Abhiyaan (the National Nutrition Mission) is a flagship programme to improve nutritional outcomes for children, adolescents, pregnant women and lactating mothers.",
   [("Targets","It aims to reduce stunting, undernutrition, anaemia and low birth weight through time-bound targets and a life-cycle approach."),
    ("Convergence and technology","The mission emphasises convergence among departments, use of technology for real-time monitoring, and community mobilisation ('Jan Andolan').")],
   "POSHAN Abhiyaan's targets (stunting, anaemia) and convergent approach are commonly tested welfare-scheme facts.",
   [("What does POSHAN Abhiyaan aim to reduce?","Stunting, undernutrition, anaemia and low birth weight."),
    ("What approach does POSHAN Abhiyaan use?","A convergent, technology-driven approach with community mobilisation.")]),

 P("nabard-explained","Body","NABARD Explained: Rural Development Bank",
   "NABARD UPSC, National Bank Agriculture Rural Development, apex bank, rural credit",
   "NABARD explained for UPSC — the apex development bank for agriculture and rural development, its refinancing role and functions.",
   "The National Bank for Agriculture and Rural Development (NABARD) is the apex development bank for agriculture and rural development in India, established in 1982.",
   [("Refinancing role","NABARD provides refinance to banks and cooperative institutions that lend for agriculture and rural activities, strengthening the rural credit system."),
    ("Development functions","It supports rural infrastructure (through funds like the RIDF), promotes self-help groups and financial inclusion, and supervises cooperative and regional rural banks.")],
   "NABARD's apex status, its 1982 establishment and its refinancing role are commonly tested economy facts.",
   [("What is NABARD's main role?","It is the apex development bank for agriculture and rural development, providing refinance and support to rural credit institutions."),
    ("When was NABARD established?","In 1982.")]),

 P("irdai-explained","Body","IRDAI Explained: India's Insurance Regulator",
   "IRDAI UPSC, Insurance Regulatory Development Authority, insurance regulator, statutory body",
   "IRDAI explained for UPSC — the statutory regulator of India's insurance sector, its objectives and functions.",
   "The Insurance Regulatory and Development Authority of India (IRDAI) is the statutory body that regulates and develops the insurance industry in India.",
   [("Mandate","IRDAI protects the interests of policyholders, regulates insurers and intermediaries, sets standards, and promotes the orderly growth of the insurance sector."),
    ("Status","It is a statutory body established under the IRDAI Act, 1999, and is headquartered in Hyderabad.")],
   "IRDAI's statutory status and role as insurance regulator are commonly tested economy-governance facts.",
   [("What does IRDAI regulate?","India's insurance sector, including insurers and intermediaries."),
    ("Is IRDAI a statutory body?","Yes, established under the IRDAI Act, 1999.")]),

 P("national-green-tribunal-ngt","Body","National Green Tribunal (NGT) Explained",
   "NGT UPSC, National Green Tribunal, environment justice, NGT Act 2010, statutory body",
   "The NGT explained for UPSC — the specialised statutory tribunal for effective and speedy disposal of environmental cases.",
   "The National Green Tribunal (NGT) is a specialised statutory body established under the NGT Act, 2010, for the effective and expeditious disposal of environmental cases.",
   [("Jurisdiction","The NGT handles cases relating to environmental protection, forests and other natural resources, and can order relief, compensation and restoration of the environment."),
    ("Significance","It applies principles like sustainable development, the polluter-pays principle and the precautionary principle, making environmental justice more accessible.")],
   "The NGT's statutory basis (2010 Act) and the principles it applies are commonly tested Environment and Polity facts.",
   [("Under which law is the NGT established?","The National Green Tribunal Act, 2010."),
    ("Which principles does the NGT apply?","Sustainable development, the polluter-pays principle and the precautionary principle.")]),

 P("enforcement-directorate-ed","Body","Enforcement Directorate (ED) Explained",
   "Enforcement Directorate UPSC, ED, PMLA, FEMA, money laundering agency",
   "The Enforcement Directorate explained for UPSC — the agency that enforces economic laws like the PMLA and FEMA against financial crime.",
   "The Enforcement Directorate (ED) is a law-enforcement and economic-intelligence agency that enforces economic laws to fight financial crime.",
   [("Key laws","The ED enforces the Prevention of Money Laundering Act (PMLA) and the Foreign Exchange Management Act (FEMA), investigating money laundering and foreign-exchange violations and attaching proceeds of crime."),
    ("Position","It functions under the Department of Revenue in the Ministry of Finance.")],
   "The ED's role under PMLA and FEMA is a commonly tested governance and economy topic.",
   [("Which laws does the Enforcement Directorate enforce?","Mainly the Prevention of Money Laundering Act (PMLA) and the Foreign Exchange Management Act (FEMA)."),
    ("Under which ministry does the ED function?","The Ministry of Finance (Department of Revenue).")]),

 P("central-bureau-of-investigation-cbi","Body","Central Bureau of Investigation (CBI) Explained",
   "CBI UPSC, Central Bureau of Investigation, DSPE Act, premier investigating agency, Santhanam",
   "The CBI explained for UPSC — India's premier investigating agency, its legal basis and the requirement of state consent.",
   "The Central Bureau of Investigation (CBI) is India's premier investigating agency, handling important criminal, corruption and special cases.",
   [("Origin and basis","The CBI was set up in 1963 and derives its powers from the Delhi Special Police Establishment (DSPE) Act, 1946. It is not a statutory body under a dedicated Act."),
    ("State consent","Since police is a State subject, the CBI generally needs the consent of a state government to investigate within that state, unless directed by a constitutional court.")],
   "The CBI's basis in the DSPE Act and the requirement of state consent are commonly tested Polity and governance facts.",
   [("Under which Act does the CBI derive its powers?","The Delhi Special Police Establishment (DSPE) Act, 1946."),
    ("Does the CBI need state consent to investigate?","Generally yes, since police is a State subject, unless a court directs otherwise.")]),

 P("financial-action-task-force-fatf","Organisation","Financial Action Task Force (FATF) Explained",
   "FATF UPSC, Financial Action Task Force, money laundering terror financing, grey list black list",
   "FATF explained for UPSC — the global watchdog against money laundering and terror financing, and its grey and black lists.",
   "The Financial Action Task Force (FATF) is an intergovernmental body that sets standards to combat money laundering, terror financing and other threats to the financial system. It was established in 1989.",
   [("Standards and lists","FATF issues recommendations that countries are expected to implement. It maintains a 'grey list' (jurisdictions under increased monitoring) and a 'black list' (high-risk jurisdictions)."),
    ("Significance","Being placed on the FATF grey or black list affects a country's access to global finance, giving FATF significant influence.")],
   "FATF's mandate and its grey/black lists are commonly tested IR and security current-affairs topics.",
   [("What does FATF combat?","Money laundering, terror financing and related threats to the financial system."),
    ("What is the FATF grey list?","A list of jurisdictions under increased monitoring for deficiencies in tackling money laundering and terror financing.")], cta="/pyq/"),

 P("asian-infrastructure-investment-bank-aiib","Organisation","Asian Infrastructure Investment Bank (AIIB)",
   "AIIB UPSC, Asian Infrastructure Investment Bank, multilateral bank, infrastructure finance",
   "AIIB explained for UPSC — the multilateral development bank focused on infrastructure in Asia, and India's role as a major member.",
   "The Asian Infrastructure Investment Bank (AIIB) is a multilateral development bank that finances infrastructure and sustainable development, headquartered in Beijing and established in 2016.",
   [("Purpose","AIIB funds infrastructure such as energy, transport, water and urban development across Asia and beyond, complementing existing institutions like the World Bank and ADB."),
    ("India and AIIB","India is one of the largest members and shareholders and a significant recipient of AIIB financing for its infrastructure projects.")],
   "AIIB's purpose, headquarters and India's role are commonly tested IR and economy facts.",
   [("Where is the AIIB headquartered?","In Beijing, China."),
    ("What does the AIIB finance?","Infrastructure and sustainable development projects, mainly in Asia.")], cta="/pyq/economy/"),

 P("asian-development-bank-adb","Organisation","Asian Development Bank (ADB) Explained",
   "ADB UPSC, Asian Development Bank, multilateral bank, Manila, development finance",
   "ADB explained for UPSC — the regional development bank promoting economic growth and cooperation in Asia and the Pacific.",
   "The Asian Development Bank (ADB) is a regional development bank established in 1966 to promote social and economic development in Asia and the Pacific. It is headquartered in Manila.",
   [("Role","ADB provides loans, technical assistance and grants for infrastructure, education, health and environmental projects, and works to reduce poverty in the region."),
    ("India and ADB","India is a founding member and a major borrower, using ADB financing for infrastructure and development projects.")],
   "ADB's headquarters (Manila), founding year and development role are commonly tested facts.",
   [("Where is the ADB headquartered?","In Manila, Philippines."),
    ("What is the ADB's main aim?","To promote social and economic development and reduce poverty in Asia and the Pacific.")], cta="/pyq/economy/"),

 P("g7-explained","Organisation","G7 Explained: Group of Seven",
   "G7 UPSC, Group of Seven, advanced economies, G7 members, global governance",
   "The G7 explained for UPSC — the grouping of major advanced economies, its members and its role in global economic and political coordination.",
   "The G7 (Group of Seven) is an informal grouping of major advanced economies that coordinate on global economic and political issues.",
   [("Members","The G7 comprises the United States, United Kingdom, France, Germany, Italy, Canada and Japan, with the European Union also participating. India is often invited as a guest."),
    ("Role","The G7 discusses global economic policy, security, climate and development, though it has no permanent secretariat and its decisions are non-binding.")],
   "The G7's membership and its distinction from the G20 are commonly tested IR facts.",
   [("Which countries are in the G7?","The US, UK, France, Germany, Italy, Canada and Japan."),
    ("Is India a member of the G7?","No, but India is frequently invited as a guest to G7 summits.")], cta="/pyq/"),

 P("oecd-explained","Organisation","OECD Explained: Organisation for Economic Co-operation",
   "OECD UPSC, Organisation Economic Co-operation Development, rich countries club, BEPS, Paris",
   "OECD explained for UPSC — the intergovernmental economic organisation of mostly developed countries, and its work on tax and policy standards.",
   "The Organisation for Economic Co-operation and Development (OECD) is an intergovernmental organisation of mostly developed economies that works to promote economic growth and better policies. It is headquartered in Paris.",
   [("Role","The OECD provides a forum for members to compare policy experiences, set standards and coordinate on issues like taxation, trade and governance. It is sometimes called a 'rich countries' club'."),
    ("Tax work","The OECD leads global work on Base Erosion and Profit Shifting (BEPS) and a global minimum corporate tax, in which India participates.")],
   "The OECD's nature and its tax-standard work (BEPS, global minimum tax) are commonly tested economy and IR topics.",
   [("Where is the OECD headquartered?","In Paris, France."),
    ("What is the OECD known for in taxation?","Leading global work on Base Erosion and Profit Shifting (BEPS) and a global minimum corporate tax.")], cta="/pyq/economy/"),

 P("new-development-bank-ndb","Organisation","New Development Bank (NDB) Explained",
   "New Development Bank UPSC, BRICS bank, NDB Shanghai, infrastructure finance",
   "The New Development Bank explained for UPSC — the BRICS-established multilateral bank for infrastructure and sustainable development.",
   "The New Development Bank (NDB) is a multilateral development bank established by the BRICS countries to fund infrastructure and sustainable development projects.",
   [("Origin and headquarters","Set up by Brazil, Russia, India, China and South Africa, the NDB is headquartered in Shanghai and has expanded its membership over time."),
    ("Purpose","It aims to mobilise resources for infrastructure and sustainable development in BRICS and other emerging economies, offering an alternative to Western-led institutions.")],
   "The NDB's BRICS origin and Shanghai headquarters are commonly tested IR and economy facts.",
   [("Who established the New Development Bank?","The BRICS countries — Brazil, Russia, India, China and South Africa."),
    ("Where is the NDB headquartered?","In Shanghai, China.")], cta="/pyq/"),

 P("forest-rights-act","Body","Forest Rights Act (FRA) Explained",
   "Forest Rights Act UPSC, FRA 2006, tribal rights, forest dwellers, gram sabha",
   "The Forest Rights Act explained for UPSC — the law recognising the rights of forest-dwelling communities over forest land and resources.",
   "The Scheduled Tribes and Other Traditional Forest Dwellers (Recognition of Forest Rights) Act, 2006 — commonly the Forest Rights Act (FRA) — recognises the rights of forest-dwelling communities.",
   [("Rights recognised","The Act recognises individual rights (to cultivate and live on forest land) and community rights (to use, manage and conserve forest resources), correcting historical injustice to forest dwellers."),
    ("Role of the Gram Sabha","The Gram Sabha plays a central role in determining and verifying claims, making the process community-driven.")],
   "The FRA's recognition of individual and community rights and the Gram Sabha's role are commonly tested environment-governance facts.",
   [("What does the Forest Rights Act recognise?","The individual and community rights of forest-dwelling communities over forest land and resources."),
    ("What role does the Gram Sabha play under the FRA?","It is central to determining and verifying claims to forest rights.")]),
]

def build(t, idx): return gt.render(t, T, idx)

def main():
    for i,t in enumerate(T):
        d=os.path.join(ROOT,"blog",t["slug"]); os.makedirs(d,exist_ok=True)
        open(os.path.join(d,"index.html"),"w").write(build(t,i))
    print("wrote",len(T),"topic posts (batch 2)")

if __name__=="__main__":
    main()
